services:
  master:
    image: saunafs-master
    container_name: "saunafs-master"
    build:
      context: ./saunafs-master
      args:
        - BASE_IMAGE=ubuntu:24.04
      secrets:
        - apt_auth
    ports:
      - "29421:9421"
    volumes:
      - ./volumes/saunafs-master/etc/saunafs:/etc/saunafs/
      - ./volumes/saunafs-master/var/lib/saunafs/:/var/lib/saunafs/
      - ./volumes/saunafs-master/var/log/:/var/log/
    networks:
      - saunafsnet

  metalogger:
    image: saunafs-metalogger
    container_name: "saunafs-metalogger"
    build:
      context: ./saunafs-metalogger
      args:
        - BASE_IMAGE=ubuntu:24.04
      secrets:
        - apt_auth
    volumes:
      - ./volumes/saunafs-metalogger/etc/saunafs:/etc/saunafs/
      - ./volumes/saunafs-metalogger/var/lib/saunafs/:/var/lib/saunafs/
      - ./volumes/saunafs-metalogger/var/log/:/var/log/
    links:
      - master:sfsmaster
    depends_on:
      - master
    networks:
      - saunafsnet

  cgi:
    image: saunafs-cgiserver
    container_name: "saunafs-cgiserver"
    build:
      context: ./saunafs-cgiserver
      args:
        - BASE_IMAGE=ubuntu:24.04
      secrets:
        - apt_auth
    ports:
      - "29425:9425"
    links:
      - master:sfsmaster
    networks:
      - saunafsnet

  chunkserver01:
    image: saunafs-chunkserver
    container_name: "saunafs-chunkserver01"
    build:
      context: ./saunafs-chunkserver
      args:
        - BASE_IMAGE=ubuntu:24.04
      secrets:
        - apt_auth
    volumes:
      - ./volumes/saunafs-chunkserver01/etc/saunafs:/etc/saunafs/
      - ./volumes/saunafs-chunkserver01/var/log/:/var/log/
      - ./volumes/saunafs-chunkserver01/var/lib/saunafs:/var/lib/saunafs
      - ./volumes/saunafs-chunkserver01/mnt/hdd001:/mnt/hdd001
      - ./volumes/saunafs-chunkserver01/mnt/hdd002:/mnt/hdd002
    links:
      - master:sfsmaster
    ports:
      - "29431:9422"
    networks:
      - saunafsnet

  chunkserver02:
    image: saunafs-chunkserver
    container_name: "saunafs-chunkserver02"
    build:
      context: ./saunafs-chunkserver
      args:
        - BASE_IMAGE=ubuntu:24.04
      secrets:
        - apt_auth
    volumes:
      - ./volumes/saunafs-chunkserver02/etc/saunafs:/etc/saunafs/
      - ./volumes/saunafs-chunkserver02/var/log/:/var/log/
      - ./volumes/saunafs-chunkserver02/var/lib/saunafs:/var/lib/saunafs
      - ./volumes/saunafs-chunkserver02/mnt/hdd001:/mnt/hdd001
      - ./volumes/saunafs-chunkserver02/mnt/hdd002:/mnt/hdd002
    links:
      - master:sfsmaster
    ports:
      - "29432:9422"
    networks:
      - saunafsnet

  chunkserver03:
    image: saunafs-chunkserver
    container_name: "saunafs-chunkserver03"
    build:
      context: ./saunafs-chunkserver
      args:
        - BASE_IMAGE=ubuntu:24.04
      secrets:
        - apt_auth
    volumes:
      - ./volumes/saunafs-chunkserver03/etc/saunafs:/etc/saunafs/
      - ./volumes/saunafs-chunkserver03/var/log/:/var/log/
      - ./volumes/saunafs-chunkserver03/var/lib/saunafs:/var/lib/saunafs
      - ./volumes/saunafs-chunkserver03/mnt/hdd001:/mnt/hdd001
      - ./volumes/saunafs-chunkserver03/mnt/hdd002:/mnt/hdd002
      - ./volumes/saunafs-chunkserver03/mnt/hdd003:/mnt/hdd003
    links:
      - master:sfsmaster
    ports:
      - "29433:9422"
    networks:
      - saunafsnet

  client:
    image: saunafs-client
    container_name: "saunafs-client"
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    build:
      context: ./saunafs-client
      args:
        - BASE_IMAGE=ubuntu:24.04
      secrets:
        - apt_auth
    command: /mnt/saunafs -H master -P 9421 -S /
    links:
      - master
    depends_on:
      - master
    volumes:
      - ./volumes/saunafs-client/var/log/:/var/log/
    networks:
      - saunafsnet

secrets:
  apt_auth:
    file: ./saunafs-apt-auth.conf

networks:
  saunafsnet:
    driver: bridge

